### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by gl33mer** [hecomi/uREPL#1]
First run. Pressed F1. Got this in the console.

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Selectable.Select () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Selectable.cs:617)
uREPL.Gui.<OpenWindow>m__260 () (at Assets/uREPL/Scripts/Core/Gui.cs:116)
uREPL.Gui+<_RunOnNextFrame>c__Iterator28.MoveNext () (at Assets/uREPL/Scripts/Core/Gui.cs:564)

**Comment by gl33mer** [comment]
The error above was received with uREPL in an empty scene (with the object added from asset menu).
I loaded the demo scene and everything seems to work. ty

**Comment by hecomi** [comment]
Thanks for the report and sorry for the inconvenience X(
I've fixed it already in the HEAD and it will be released soon as v0.1.0 with some new functions.

**Comment by gl33mer** [comment]
No worries. TY for sharing.
