### ISSUE TITLE
ReadonlyFieldItem null checks

### ISSUE THREAD

**Issue by zhdiv** [hecomi/uREPL#10]
Hi,
ReadonlyFieldItem class require additional null check. Something like:
protected set { valueText.text = value==null ? "Null" : value.ToString(); }
Got error with null reference exception if field is unassigned.

And if it possible do not display null message in console at Window.OnSubmit() if result.type == CompileResult.Type.Success

And of course big thanks for asset.

**Comment by hecomi** [comment]
Sorry for my late reply...
I've fixed the null check, thank you for the suggestion.
This fix will be included in the next release.

Regarding the null output, I want to think more about it because uREPL cannot distinguish below scenarios:

```cs
$ var obj = GameObject.Find("Cube");
> null
```

```cs
$ object obj;
> null
$ obj; // user wants to check obj is null or not.
> null
```

**Comment by hecomi** [comment]
Released:
https://github.com/hecomi/uREPL/releases/tag/v0.5.1
