### ISSUE TITLE
Inspect() not work in Net 4.6

### ISSUE THREAD

**Issue by kairipton** [hecomi/uREPL#11]
Hi.
I am using Unity 2017.1 version.
I am using Net 4.6, but the Inspect method does not work.
It works fine in Net 3.5.
I hope that this problem will be corrected later.
And thank you for making this asset.
This asset is REALLY AWSOME.

**Comment by kairipton** [comment]
It works fine in v0.5.0.
Thank you.

**Comment by hecomi** [comment]
Thank you for the report and the check!
