### ISSUE TITLE
Android cannot enter command input

### ISSUE THREAD

**Issue by HyVong007** [hecomi/uREPL#13]
I have tested successfully on Unity player and windows standalone build. But when on Android build, I can touch on Input field and type letter, but when I press Enter the uREPL doesnot execute.

**Comment by hecomi** [comment]
Sorry for my late reply...
I've fixed this problem in this commit:
https://github.com/hecomi/uREPL/commit/a27b399a3a9eeb4180ea7c203ce89717ce8b006f

**Comment by HyVong007** [comment]
Thank you so much ! I very love your asset. I think you should bring it to
Unity Asset Store, many people will like it 😍
Hope you are going to develop uREPL in the future !

Vào 13:09 Th 7, 17 thg 11 2018 hecomi <notifications@github.com> đã viết:
