### ISSUE TITLE
Unity 2018.1 support

### ISSUE THREAD

**Issue by marcinbiegun** [hecomi/uREPL#14]
uREPL is not working in latest stable Unity build. I'm getting this error:

`Assets/uREPL/Scripts/Core/Mono.cs(34,22): error CS0234: The type or namespace name 'CSharp' does not exist in the namespace 'Mono'. Are you missing an assembly reference?`

**Comment by hecomi** [comment]
Sorry for my late reply...
I tested uREPL with Unity 2018.2.15f1 and it worked well. Could you check the API compatibility setting in your project?
<img width="369" alt="api" src="https://user-images.githubusercontent.com/493433/48658091-54d82e00-ea7f-11e8-8041-e04fb26c4c5d.PNG">

From v0.5.0, uREPL only supports .NET 4.X, so if you are using the .NET 2.0, please use v0.4.0. Now I close this issue, but if you have any other problem, please reopen and let me know it.
