### ISSUE TITLE
Auto-Load Namespaces. 

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [hecomi/uREPL#15]
I find myself loading a few namespaces always. Is there a way to specify(maybe through scripting) a list of namespaces to auto load.

**Comment by Kabie** [comment]
I'm using a simple script to achieve this.

```
using UnityEngine;
using uREPL;

public class ReplPreload : MonoBehaviour
{
    public string[] Commands;

    void Start()
    {
        foreach (var command in Commands)
        {
            Evaluator.Evaluate(command);
        }
    }
}

```

**Comment by hecomi** [comment]
Sorry for my late work..., but I've added `Pre-Load Command` text area to `uREPL.Main` component from v0.6.0. The code written here is run just after starting scene like @Kabie wrote above.
https://github.com/hecomi/uREPL/releases/tag/v0.6.0

Please write here namespaces which you want to use like below:
```cs
using UnityEngine.UI;
using UnityEngine.XR;
```
