### ISSUE TITLE
How to re-open uRepl Window after using close command?

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [hecomi/uREPL#16]

**Comment by kersk** [comment]
Ran into this, too. It's not documented yet, but the default key to toggle is F1. I quickly rebound it to ~ (as it should be!). :)

**Comment by hecomi** [comment]
Sorry for my late reply and thank you @kersk !
As @kersk said, the default key is F1 and you can change it from the inspector:
https://github.com/hecomi/uREPL/blob/master/Assets/uREPL/Scripts/Gui/Window/KeyBinding.cs#L42-L43
