### ISSUE TITLE
This is incredibly cool! Requests inside.

### ISSUE THREAD

**Issue by Polyrhythm** [hecomi/uREPL#2]
Hey! I really REALLY want to use this as a sort of live-coding app with my Hololens. To make this happen, the only thing I think I'd really want is the multiline support so that I can evaluate entire scripts rather than single lines. Do you think something like this is doable?

I'm happy to put some work in and make a Hololens-compatible example using this so that I can hack on a 3d scene in AR.

**Comment by hecomi** [comment]
Thank you for the comment!
To support the multiline function, many code changes were needed..., so I gave up trying to support it before.
But this time, I want to try because I also want to see how effective the REPL is in the 3D scene in AR.
Please wait for some days...

**Comment by hecomi** [comment]
Sorry for the delay..., but I finished the refactoring and added some functions including the multi-line support in v0.3.0 😄.
Please download and try it:
- https://github.com/hecomi/uREPL/releases/tag/v0.3.0

**Comment by Polyrhythm** [comment]
Yes! Can't wait to try.

**Comment by Polyrhythm** [comment]
Closing because multi-line is in. =)
