### ISSUE TITLE
MainEditor not excluded at build time

### ISSUE THREAD

**Issue by robin-moss** [hecomi/uREPL#25]
When installing uREPL via the Git URL the `MainEditor` is no longer under the special `Editor` folder under assets, as so it's not actually excluded at build time.

This leads to the build failing because of the dependency on `UnityEditor`

To solve this we would need to modify the package to add `#if (UNITY_EDITOR)`  around the entire file.

Could you update the `MainEditor` to use macros please?

**Comment by hecomi** [comment]
Thank you for the report! I'll fix it soon.

**Comment by hecomi** [comment]
`uREPL.Editor.asmdef` was added and the problem was fixed from v1.0.4.
https://github.com/hecomi/uREPL/releases/tag/v1.0.4

**Comment by robin-moss** [comment]
Thank you, it works now
