### ISSUE TITLE
0.3 release doesn't include some necessary folders

### ISSUE THREAD

**Issue by Polyrhythm** [hecomi/uREPL#3]
The unitypackage release is missing some folders in uREPL/Resources/Prefabs/ that make it crash on completing a command. I had to get it working by cloning master into my project.

**Comment by hecomi** [comment]
I'll update the package after fixing #5.

**Comment by hecomi** [comment]
v0.3.1 includes missing contents.
https://github.com/hecomi/uREPL/releases/tag/v0.3.1
