### ISSUE TITLE
Random crashes and loss of autocomplete

### ISSUE THREAD

**Issue by Polyrhythm** [hecomi/uREPL#5]
On Unity 5.4.x and Windows I get random crashes with uREPL while using it. I know a crash is imminent because the repl loses all autocomplete functionality and whatever command I evaluate next will usually crash Unity completely.

I haven't been able to find any particular patterns as to why it crashes yet.

**Comment by hecomi** [comment]
Thanks for the report.
I guess this is caused by something broken in the autocompletion thread.
I'll check it soon.

**Comment by hecomi** [comment]
What OS are you using?

**Comment by Polyrhythm** [comment]
I'm on Windows 10

**Comment by hecomi** [comment]
I found `Mono.CSharp.Evaluator.GetCompletions()` causes blocking when a certain code like `for (` is given to it. I commented out the whole code evaluation to avoid this case. Could you try the latest package?
- [uREPL.zip](https://github.com/hecomi/uREPL/files/492941/uREPL.zip)

**Comment by Polyrhythm** [comment]
Looks like you fixed it. 👍

**Comment by hecomi** [comment]
Sorry for my late reply..., I released v0.3.1 including the above fix.
https://github.com/hecomi/uREPL/releases/tag/v0.3.1
