### ISSUE TITLE
Completions for global namespace

### ISSUE THREAD

**Issue by kgooble** [hecomi/uREPL#7]
Hi, this project is super cool! I was testing it out and noticed that if I add classes in the global namespace, they do not show up for auto completion. Do you know why that is? If I add the class to a namespace and add the namespace to the Mono evaluator, the class shows up for autocompletion.

Thanks!

**Comment by hecomi** [comment]
Thanks for the report! I haven't noticed it... X( I'll investigate the cause of that bug.

**Comment by hecomi** [comment]
I couldn't find the way to do the global class comletion with `Mono.CSharp.Evaluator.GetCompletions()`. Instead of that, I added new completion plugin that finds global classes from all assemblies. Could you check the latest commit?

**Comment by kgooble** [comment]
Fantastic! Thanks @hecomi, it works great as far as I can tell so far!

**Comment by hecomi** [comment]
Thanks for the test! I'll add it to release page as .unitypackage later. If you'll find some problem, please let me know ;).
