### ISSUE TITLE
Errors using NET 4.6

### ISSUE THREAD

**Issue by EnricoMonese** [hecomi/uREPL#9]
Using the new NET 4.6 in Unity 2017 produces errors on runtime
Maybe a newer Mono.CSharp dll is needed
![schermata 2017-08-27 alle 16 57 34](https://user-images.githubusercontent.com/19847464/29750941-e116389a-8b48-11e7-92d7-cbaee7617749.png)

> NullReferenceException: Object reference not set to an instance of an object
Mono.CSharp.PredefinedAttribute.Resolve (System.Boolean canFail) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.TypeManager.IsThisOrFriendAssembly (System.Reflection.Assembly assembly) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.Namespace.RegisterExternalExtensionMethodClass (System.Type type) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.RootNamespace.RegisterExtensionMethodClass (System.Type t) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) (at <4e00b9119e4142deb005b807dc024965>:0)
Mono.CSharp.Evaluator.ReferenceAssembly (System.Reflection.Assembly a) (at <4e00b9119e4142deb005b807dc024965>:0)
uREPL.Evaluator.ReferenceAllAssemblies () (at Assets/uREPL/Scripts/Core/Evaluator.cs:50)
uREPL.Evaluator.Initialize () (at Assets/uREPL/Scripts/Core/Evaluator.cs:36)
uREPL.Main.Awake () (at Assets/uREPL/Scripts/Core/Main.cs:14)

> NullReferenceException: Object reference not set to an instance of an object
uREPL.Window.get_parameters () (at Assets/uREPL/Scripts/Gui/Window/Window.cs:25)
uREPL.CompletionView.UpdateAnnotation () (at Assets/uREPL/Scripts/Gui/Window/CompletionView.cs:117)
uREPL.CompletionView.Update () (at Assets/uREPL/Scripts/Gui/Window/CompletionView.cs:100)

**Comment by hecomi** [comment]
Sorry for my late reply..., and thank you for the reporting.
I've just started investigating how to fix this problem.

**Comment by hecomi** [comment]
v0.5.0 supports .NET 4.6 now:
https://github.com/hecomi/uREPL/releases/tag/v0.5.0
